### PR TITLE
Parse DEVICE_ANNOUNCE header correctly

### LINKED ISSUE #327: Clipboard and drive redirection are broken when "Printers" is selected as a shared local resource
This but is just combining #308 and #312 
When using the Microsoft Remote Desktop Connection Client.  
If "Printers" is selected as a local shared resource under the "Local Resources" tab it somehow breaks both the clipboard and drive redirection through thinclient_drives.  

It feels like something that could be addressed server side, or is not being account for on the server side.  Hoping for a fix.

### PR DESCRIPTION
**Pull request by matt335672**
Fixes #327 

The DEVICE_ANNOUNCE header in [[MS-RDPEFS] 2.2.1.3](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpefs/32e34332-774b-4ead-8c9d-5d64720d6bf9) has DeviceDataLength and DeviceData fields. These fields are only parsed correctly for devices of type RDPDR_DTYP_FILESYSTEM

For all other device types, the fields are not read and skipped, but are left sitting in the buffer.

Consequently, when a [DR_DEVICELIST_ANNOUNCE](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpefs/d8b2bc1c-0207-4c15-abe3-62eaa2afcaf1) message is received with a printer before the filesystem drives, chansrv gets out of sync and fails to parse the filesystem drives correctly.

This PR skips the DeviceDataLength and DeviceData fields correctly for all device types.

Incidentally, I'm not aware of why devredir.c uses xstream macros from parse.h rather than the more usual ones. I've added another xstream macro `xstream_skip_u8` to allow a number of bytes in the data stream to be skipped.

As I submit this, the CI for 32-bit builds is still broken.

### CODE REVIEW

**Comment by matt335672** [comment]
CI is now working again.

I've improved the logging on this a little.

On my test machine (debug logging enabled) I get the following in the chansrv log while enabling remote printer support:-

```
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Remote printer 'PRN2' is not supported and will be ignored
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Remote printer 'PRN6' is not supported and will be ignored
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Remote printer 'PRN5' is not supported and will be ignored
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Remote printer 'PRN4' is not supported and will be ignored
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Remote printer 'PRN3' is not supported and will be ignored
[20210903-13:55:43] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] detected remote drive C:
```

File: sesman/chansrv/devredir.c [hunk 1]
```diff
@@ -814,18 +814,24 @@ devredir_proc_client_devlist_announce_req(struct stream *s)
...
                 /* get device data len */
-                xstream_rd_u32_le(s, device_data_len);
                 if (device_data_len)
                 {
                     xstream_rd_string(g_full_name_for_filesystem, s,
                                       device_data_len);
                 }
 
-                LOG_DEVEL(LOG_LEVEL_DEBUG, "device_type=FILE_SYSTEM device_id=0x%x dosname=%s "
+                LOG(LOG_LEVEL_INFO, "detected remote drive %s",
```
Comment (metalefty) [inline sesman/chansrv/devredir.c]:
```
[20210906-08:30:58] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] detected remote drive tmp
```

`"detected remote drive: %s"` will be more readable.

Comment (metalefty) [reply sesman/chansrv/devredir.c]: I would be also fine like smartcard one.

```
  LOG(LOG_LEVEL_INFO, "Detected remote smartcard '%s'",
```

Also, capitalize it.

**Comment by metalefty** [comment]
I confirmed it fixes drive redirection. It is working fine now. LGTM except for some trivial points on logging.

**Comment by matt335672** [comment]
I've also changed the 'not supported' message to look like the others.

I get the following now on log-on, with everything redirected from the client. Debug logging is enabled.

```
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] detected remote PRINTER 'PRN3' (not supported)
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] detected remote PRINTER 'PRN7' (not supported)
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] detected remote PRINTER 'PRN6' (not supported)
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] detected remote PRINTER 'PRN5' (not supported)
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] detected remote PRINTER 'PRN4' (not supported)
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] detected remote FILE_SYSTEM 'D:'
[20210908-11:45:34] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] detected remote FILE_SYSTEM 'C:'
```

**Comment by matt335672** [comment]
My bad - I misunderstood what you meant by capitalisation. My fault.

Log messages are now:-

```
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN3' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN7' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN6' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN5' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN4' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] Detected remote drive 'D:'
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] Detected remote drive 'C:'
```

**Comment by metalefty** [comment]
```
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:871)] Detected remote printer 'PRN4' (not supported)
[20210908-11:52:46] [INFO ] [devredir_proc_client_devlist_announce_req(devredir.c:830)] Detected remote drive 'D:'
```

Yes, that is what I meant.  The smartcard log was capitalized and drive redirection log was not capitalized. I actually wanted to say either "Detected" or "detected" is fine but should be consistent.

**Review by metalefty — APPROVED** [review]
