### PR TITLE
clipboard file: Implement MS-RDPECLIP 3.1.5.4.7 compliance

### LINKED ISSUE #1997: clipboard file: xrdp is not responding CB_RESPONSE_FAIL even if it failed
When `clipboard_send_file_data` fails due to the file is not readable or other reasons, the client waits to finish file transfer forever. Maybe we need to abort file transfer gracefully. 

スクリーンショット 2021-09-15 15 36 12

```
meta@xrdp:~/xrdp$ tail -f ~/.local/share/xrdp/xrdp-chansrv.10.log
[20210915-06:35:14] [DEBUG] [process_message_channel_data(chansrv.c:446)] process_message_channel_data: chan_id 2 chan_flags 19
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1523)] clipboard_data_in: chan_id 2 chan_flags 0x13 length 32 total_length 32 in_request 0 g_ins->size 8192
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1586)] clipboard_data_in: clip_msg_id 8 clip_msg_status 0 clip_msg_len 24
[20210915-06:35:14] [DEBUG] [clipboard_data_in(clipboard.c:1591)] clipboard_data_in: 8
[20210915-06:35:14] [DEBUG] [clipboard_process_file_request(clipboard_file.c:508)] clipboard_process_file_request:
[20210915-06:35:14] [DEBUG] [clipboard_send_file_data(clipboard_file.c:408)] clipboard_send_file_data: streamId 24422 lindex 0 nPositionLow 0 cbRequested 34520
[20210915-06:35:14] [ERROR] [clipboard_send_file_data(clipboard_file.c:415)] clipboard_send_file_data: file open [/home/meta/Downloads/paper.docx] failed
[20210915-06:35:14] [DEBUG] [scard_pcsc_check_wait_objs(smartcard_pcsc.c:401)] scard_pcsc_check_wait_objs:
[20210915-06:35:14] [DEBUG] [scard_pcsc_get_wait_objs(smartcard_pcsc.c:374)] scard_pcsc_get_wait_objs:
[20210915-06:35:14] [DEBUG] [get_timeout(chansrv.c:153)] get_timeout:
```

I haven't read MS-RDPECLIP corner to corner yet however I guess xrdp should respond to [ File Contents Request PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/cbc851d3-4e68-45f4-9292-26872a9209f2) with [File Contents Response PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/df87c178-ab02-471a-acde-bb921aa1af85) that contain `CB_RESPONSE_FAIL` to indicate "the request could not be satisfied". 

I quickly performed `git grep CB_RESPONSE_FAIL` but it was not used in `clipboard_file.c` at all.  The return value of `clipboard_send_file_size` and `clipboard_send_file_data` should be checked and xrdp should return `CB_RESPONSE_FAIL` when they failed.

https://github.com/neutrinolabs/xrdp/blob/23742dbb8ef4f3a0b2d7d911bafd09153c6193da/sesman/chansrv/clipboard_file.c#L496-L526

### PR DESCRIPTION
**Pull request by metalefty**
If the requested file data could not be retrieved or the sender received
an unsuccessful Format List Response PDU (section 3.1.5.2.4), then the
clipHeader field MUST contain the CB_RESPONSE_FAIL (0x0002) flag and the
requestedFileContentsData field MUST contain no data (zero-length).

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/5d3991e9-440d-4e4d-8b8d-391c324c4007

Fixes #1997.

### CODE REVIEW

**Comment by metalefty** [comment]
If files are not readable due to insufficient permission, 
```
-rw------- 1 root root 34520 Sep  8 04:06 /home/meta/Downloads/paper.docx
```

## Before this PR
The client waits for file transfer infinitely.
スクリーンショット 2021-09-21 171956

## This PR fixes
File transfer fails immediately.
スクリーンショット 2021-09-21 172005

File: sesman/chansrv/clipboard_file.c [hunk 1]
```diff
@@ -318,12 +349,20 @@ clipboard_send_file_size(int streamId, int lindex)
...
     cfi = (struct cb_file_info *)list_get_item(g_files_list, lindex);
     if (cfi == 0)
     {
         LOG_DEVEL(LOG_LEVEL_ERROR, "clipboard_send_file_size: error cfi is nil");
+        clipboard_send_filecontents_response_fail(streamId);
+        return 1;
+    }
+    if (cfi->size < 0)
+    {
+        LOG(LOG_LEVEL_ERROR, "clipboard_send_file_size: failed to get file size");
```
Comment (matt335672) [inline sesman/chansrv/clipboard_file.c]: Suggest reporting the value of the size here, so we can diagnose problems where the file is between 2 and 4GB in size. As we've been discussing [here](https://github.com/neutrinolabs/xrdp/discussions/1987) this is awkward for us at the moment.

File: sesman/chansrv/clipboard_file.c [hunk 2]
```diff
@@ -412,15 +453,17 @@ clipboard_send_file_data(int streamId, int lindex,
...
-        LOG_DEVEL(LOG_LEVEL_ERROR, "clipboard_send_file_data: file open [%s] failed",
-                  full_fn);
+        LOG(LOG_LEVEL_ERROR, "clipboard_send_file_data: file open [%s] failed: %s",
+            full_fn, g_get_strerror());
+        clipboard_send_filecontents_response_fail(streamId);
         return 1;
     }
     if (g_file_seek(fd, nPositionLow) < 0)
     {
         LOG_DEVEL(LOG_LEVEL_ERROR, "clipboard_send_file_data: seek error "
```
Comment (matt335672) [inline sesman/chansrv/clipboard_file.c]: The logging call for a seek fail should definitely be a LOG() rather than a LOG_DEVEL(). Suggest also using g_get_strerror() to get the error from the seek operation.

File: sesman/chansrv/clipboard_file.c [hunk 3]
```diff
@@ -412,15 +453,17 @@ clipboard_send_file_data(int streamId, int lindex,
...
                   "in file: %s", full_fn);
         g_file_close(fd);
+        clipboard_send_filecontents_response_fail(streamId);
```
Comment (matt335672) [inline sesman/chansrv/clipboard_file.c:467]: Also, suggest the LOG_DEVEL() above this call (your line 463) is a LOG() instead.

**Review by matt335672 — COMMENTED** [review]
LGTM. Couple of minor comments around logging.

File: sesman/chansrv/clipboard_file.c (hunk 1 above)
Comment (metalefty) [reply sesman/chansrv/clipboard_file.c]: Thanks, I intended to catch the error of `stat` but indeed it will be recognized as a negative value if the size is between 2 and 4GB.
https://github.com/neutrinolabs/xrdp/blob/85518a81574e3153f266b4d66138f7a772450eee/common/os_calls.c#L2501-L2508

**Comment by metalefty** [comment]
Addressed review comments.
