### PR TITLE
Chansrv hang fix

### LINKED ISSUE #1563: copy/paste file through clipboard doesn't work on Ubuntu 16.04.6
Hello,

I can't copy/paste files from windows host  to Ubuntu remote by Ctrl+C Ctrl+V.

I built xrdp from source (v0.9.13) (with jpeg, fuse & rfxcodec) and it's running on an Ubuntu 16.04.6 VM.
RDP client is built-in remote desktop from Windows 10 with clipboard & drive mapping enabled.

I can see my drives into the mount point thinclient_drives, I can transfert file in it.
Clipboard for text also work in both direction.
I look into the folder thinclient_drives/.clipboard and  no file appears after Ctrl+C (in any side).
Log file at ~/.local/share/xrdp/xrdp-chansrv.XX.log : 

`[20200501-14:47:14] [CORE ] main: app started pid 1336(0x00000538)
[20200501-14:47:14] [INFO ] main: DISPLAY env var set to :10.0
[20200501-14:47:14] [INFO ] main: using DISPLAY 10
[20200501-14:47:14] [INFO ] channel_thread_loop: thread start
[20200501-14:47:14] [INFO ] Socket 12: AF_UNIX connection received
[20200501-14:47:42] [ERROR] clipboard_event_selection_request: unknown target GTK_TEXT_BUFFER_CONTENTS
[20200501-14:49:08] [INFO ] channel_thread_loop: trans_check_wait_objs error resetting
[20200501-14:49:59] [INFO ] Socket 12: AF_UNIX connection received
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 18/0 resource 0x120072b
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 25/0 resource 0x120072b
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 18/0 resource 0x1200775
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 25/0 resource 0x1200775
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 18/0 resource 0x120079b
[20200501-14:49:59] [ERROR] X error [BadWindow (invalid Window parameter)](3) opcodes 25/0 resource 0x120079b
[20200501-14:50:18] [INFO ] channel_thread_loop: trans_check_wait_objs error resetting
[20200501-14:53:57] [INFO ] Socket 12: AF_UNIX connection received`

Is there a solution?

xrdp : **0.9.13**
xorgxrdp: **0.2.13**
Ubuntu: **16.04.6**

Thanks

### LINKED ISSUE #2031: Using GUI to copy file in thinclient_drives hangs chansrv hard
I should have raised this earlier - apologies for that.

I noted in #1563 that:-

> When I CTRL-C on a file under `thinclient_drives`, chansrv execution enters `clipboard_get_file()` from where it calls
> `g_directory_exist()`. This results in a `stat()` system call which needs to be serviced by chansrv, but it can't be as it's still
> servicing the copy request.

A hung chansrv is bad enough, but I've lately realised that the implications of this are a lot worse than I realised. chansrv hangs hard when this happens and doesn't respond to SIGTERM. As a result the logic to end the session in session.c gets stuck in g_waitpid_status() waiting for chansrv to exit:-

https://github.com/neutrinolabs/xrdp/blob/e867c925d5f002d80c2d1ca4422ef70b68848b4c/sesman/session.c#L900-L910

As a result of this, sesman doesn't get the SIGCHLD from the session exiting, and the user is unable to log in again, as sesman tells them to connect to a session which is no longer there. This can produce artefacts like that noted in #2021

### PR DESCRIPTION
**Pull request by matt335672**
Fixes #2031 

Before chansrv adds a UN*X file system path to the Windows clipboard, it checks that the file is not already remote (i.e. on a Windows filesystem).

There is no point in adding these files to the Windows clipboard as they are already on the remote system. Note that the files are in any case still added to the UN*X clipboard, so cut-paste functionality within the remote session works as expected.

Without this fix, selecting file in the remote filesystem and hitting CTRL-C hangs chansrv hard.

With the fix, it is possible to use the Unix desktop copy-paste functionality to copy files from the remote filesystem.

### CODE REVIEW

File: common/os_calls.c [hunk 1]
```diff
@@ -2510,6 +2510,50 @@ g_file_get_size(const char *filename)
 #endif
 }
 
+/*****************************************************************************/
+/* returns device number, -1 on error */
+int
+g_file_get_device_number(const char *filename)
+{
+#if defined(_WIN32)
```
Comment (metalefty) [inline common/os_calls.c:2518]: To be discussed in a separate issue, it might be time to discuss such Win32 hack is still needed. 

As I already clarified [Plat form Support Titer](https://github.com/neutrinolabs/xrdp/wiki/Platform-Support-Tier), Windows support is not maintained for years. I will raise a new discussion for this.

**Comment by metalefty** [comment]
It makes sense. Let's go ahead.

**Review by metalefty — APPROVED** [review]
