### PR TITLE
sesman: address the issue of socket file leftovers

### LINKED ISSUE #1740: sometimes fails to delete some socket files
```
$ grep cleanup_sockets /var/log/xrdp-sesman.log
[20201130-18:16:48] [DEBUG] cleanup_sockets:
[20201130-18:16:48] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_audio_out_socket_10
[20201130-18:16:48] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_audio_in_socket_10
[20201130-18:16:48] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
[20201130-18:19:46] [DEBUG] cleanup_sockets:
[20201130-18:19:46] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_10
[20201202-15:36:04] [DEBUG] cleanup_sockets:
[20201202-15:36:04] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_10
[20201202-15:36:04] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
[20201202-15:36:04] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpapi_10
[20201202-15:37:33] [DEBUG] cleanup_sockets:
[20201202-15:37:33] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_audio_out_socket_10
[20201202-15:37:33] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_audio_in_socket_10
[20201202-15:37:33] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
[20201202-15:39:41] [DEBUG] cleanup_sockets:
[20201202-15:39:41] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_10
[20201202-15:39:42] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdp_chansrv_socket_10
```

This prevents reusing display number `:10` until socket files removed (by system reboot). See  [sesman/session.c around L165](https://github.com/neutrinolabs/xrdp/blob/v0.9.14/sesman/session.c#L165).

If the system is working for a long time, usable sessions will be diminished due to such orphaned socket files. Finally, the number of orphaned sessions reach `MaxSessions`, new sessions cannot be created even the number of actually running sessions is less than `MaxSessions`. 

Thus `cleanup_sockets` needs to be more robust.

### PR DESCRIPTION
**Pull request by metalefty**
There are two points.

Make sure cleanup files happen after chansrv and Xserver exit. If these
child processes lock socket files, the deletion might fail.

Usually, cleanup of xorgxrdp related socket files is handled by
xorgxrdp. Just in case it failed, perform cleanup also in sesman.

Fixes #1740. Thanks to @matt335672.

Sponsored by:   Cybertrust Japan
Sponsored by:   HAW International

### CODE REVIEW

**Comment by metalefty** [comment]
I would like to ship this to v0.9.15.

File: sesman/session.c [hunk 1]
```diff
@@ -1199,6 +1204,33 @@ cleanup_sockets(int display)
...
+     * but just in case the deletion failed */
+
+    g_snprintf(file, 255, XRDP_X11RDP_STR, display);
+    if (g_file_exist(file))
+    {
+        LOG(LOG_LEVEL_DEBUG, "cleanup_sockets: deleting %s", file);
+        if (g_file_delete(file) == 0)
+        {
+            LOG(LOG_LEVEL_DEBUG,
+                "cleanup_sockets: failed to delete %s", file);
```
Comment (matt335672) [inline sesman/session.c:1217]: Couple of suggestions here:-
1. Use `LOG_LEVEL_WARNING` instead of `LOG_LEVEL_DEBUG` for the deletion failure.
2. Use something like `"cleanup_sockets: failed to delete %s: %s", file, g_get_strerror());` to log the error condition. This would apply to all the deletions in `cleanup_sockets()`

**Review by matt335672 — COMMENTED** [review]
Looks good - minor suggestions

**Review by matt335672 — APPROVED** [review]

File: sesman/session.c (hunk 1 above)
Comment (metalefty) [reply sesman/session.c:1217]: Good point.
