### PR TITLE
xrdp: get port from configfile in access_control()

### LINKED ISSUE #894: xrdp hard coded port for sesman, config settings are not fully read
After changing Globals/ListenPort in sesman.ini to a number other than 3350, clients show an error:
`"Reply from access control: Error connecting to PAM"`
and the next line is logged to xrdp.log:
`[20170926-10:34:23] [ERROR] Failure connecting to socket sesman`

It seems the issue is caused due to the sesman port hard coded to 3350 in xrdp/xrdp_mm.c, access_control(). My colleague  @osalvadorvilardaga has a patch for it which works fine in test environments.

### PR DESCRIPTION
**Pull request by osalvadorvilardaga**
This fixes #894

access_control() does not read the port from the configuration file and it uses a hardcoded port instead.
So,  in case we use another port which is not the default one(3350), we are going to fail while connecting.

### CODE REVIEW

File: xrdp/xrdp_mm.c [hunk 1]
```diff
@@ -1471,11 +1471,13 @@ access_control(char *username, char *password, char *srv)
     unsigned long size;
     int index;
     int socket = g_tcp_socket();
+    char port[8];
 
     if (socket != -1)
     {
+	xrdp_mm_get_sesman_port(port, sizeof(port));
```
Comment (metalefty) [inline xrdp/xrdp_mm.c]: Indent.

**Comment by metalefty** [comment]
Good catch! Looks good to me.

**Comment by osalvadorvilardaga** [comment]
Is there anything else I can do here?

**Comment by jsorg71** [comment]
+1

There is more to do, sesman should use common/trans and we should use a unix domain socket for xrdp <-> sesman since they are run on the same machine.

**Comment by osalvadorvilardaga** [comment]
@jsorg71 About the common/tranns, I guess you mean changing sesman_listen_test() and sesman_main_loop() functions to use trans_* functions.
But maybe we want to merge first this.

**Comment by jsorg71** [comment]
Yes, for sure.

**Comment by metalefty** [comment]
Thanks, I think there's no problem on this PR now.

**Comment by metalefty** [comment]
Let's merge. Then think about using unix domain socket as Jay say.
